name: unit test
description: unit test module

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        check-latest: true
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - name: unit Test
      working-directory: .
      run: |
        go test ./...
      shell: bash
