apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-proxy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-proxy-api
  template:
    metadata:
      labels:
        app: github-proxy-api
    spec:
      containers:
        - name: github-proxy-api
          image: ghcr.io/andrelince/github-proxy-api@${DIGEST}
