apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-images
spec:
  validationFailureAction: Enforce # Use the capitalized "Enforce" instead of "enforce"
  background: true
  rules:
    - name: verify-signature
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - image: "ghcr.io/andrelince/*"
          key: "k8s://kyverno/cosign-public-key"
